# ===============================
# Application Configuration
# ===============================
spring.application.name=book_library
server.port=8085

# ===============================
# MongoDB Configuration (Dockerized)
# ===============================
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Logging Configuration
# ===============================
logging.file.name=/logs/book-library-app.log
logging.level.root=INFO
logging.level.com.neeraj.book_library=DEBUG

# Optional: Log rotation
# logging.logback.rollingpolicy.file-name-pattern=/apps/logs/book-library-app.%d{yyyy-MM-dd}.log
 logging.logback.rollingpolicy.file-name-pattern=/logs/book-library-app.%d{yyyy-MM-dd}.%i.log

 logging.logback.rollingpolicy.max-history=7
 logging.logback.rollingpolicy.total-size-cap=50MB

# ===============================
# Pagination Defaults
# ===============================
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50
